belnuweb/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Panel de administracion'

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from . import views
from .api import VariationApiView

urlpatterns = [
    path('', views.store, name="store"),
    path('category/<slug:category_slug>/', views.store, name='product_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/<slug:product_slug>/<int:edicion>/', views.product_detail_2, name='product_detail_2'),
    path('search/', views.search, name='search'),
    path('buscar_titulo/<int:product>/<int:edicion>/',VariationApiView.as_view(),name="variation_api"), # url para ajax de buscar titulo + edicion
    path('get_ajax_titulo/', views.get_ajax_titulo , name = "get_ajax_titulo"), # url para ajax de buscar titulo
    path('nuevo_producto/', views.nuevo_producto, name='nuevo_producto'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

store/models.py
from tabnanny import verbose
from django.db import models
from category.models import Category
from accounts.models import Account
from django.db.models import Avg, Count
from django.urls import reverse
import computed_property


# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200,unique=True,verbose_name='Nombre Producto')
    slug = models.SlugField(max_length=200)
    description = models.CharField(max_length=500,blank=True,verbose_name='Descripción',null=True)
    price = models.DecimalField(max_digits=18,decimal_places=2,verbose_name='PVP')
    recargo_interior = models.DecimalField(max_digits=18,decimal_places=2,verbose_name='Recargo Interior')
    porcentaje_vv = models.DecimalField(max_digits=18,decimal_places=2,verbose_name='% Vendedor')
    images = models.ImageField(upload_to='photos/products',verbose_name='Imagen')
    #stock = computed_property.ComputedIntegerField(compute_from='stock_total',verbose_name="Stock")
    stock_p=models.IntegerField(verbose_name="Stock_p",default=1)
    is_available = models.BooleanField(default=True,verbose_name='Disponible')
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='Categoria')
    created_date = models.DateField(auto_now_add=True,verbose_name='Fecha de creacion')
    modified_date = models.DateField(auto_now=True,verbose_name='Fecha de actualizacion')
    

        
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['product_name', '-created_date']
    
    
    def __str__(self):
        return self.product_name
    
    def get_url(self):
        try:
            return reverse('product_detail', args=[self.category.slug, self.slug])
        except:
            pass
        
    @property    
    def stock(self,stock=0):
        ediciones = Variation.objects.filter(product=self.id)        
        print(ediciones.count())
        print(ediciones)
        i=0
        for x in ediciones:
            i +=1
            print("titulo: ", str(x.id))
            print("titulo", x.product.product_name)
            print("edicion: ", x.variation_value)
            print("el stock es "+ str(x.stock))
                
            stock += x.stock
            print("stock parcial:"+str(stock))
            print(i)
        if stock is not None:
            print("el stock total seria="+str(stock))
            return stock      
        class Meta:
            verbose_name = "Stock"   
        

    @property
    def pvp_total(self):
        try:
            return self.price + self.recargo_interior
        except:
            pass
        
    @property
    def precio_vv(self):
        try:
            return (self.price*self.porcentaje_vv/100) + self.recargo_interior
        except:
            pass
        
    @property
    def averageReview(self):
        try:
            reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
            avg=0
            if reviews['average'] is not None:
                avg = float(reviews['average'])
            return avg
        except:
            pass
        
    @property
    def countReview(self):
        try:
            reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
            count=0
            if reviews['count'] is not None:
                count = int(reviews['count'])

            return count
        except:
            pass
 
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Valoracion"
        verbose_name_plural = "Valoraciones"
        ordering = ['rating']
    
    def __str__(self):
        return self.subject

variation_category_choices = (
                                ('Edicion', 'Edicion'),
                            )

class VariationManager(models.Manager):
    def edicion(self):
        return super(VariationManager, self).filter(variation_category="Edicion",is_active=True)
    


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='Producto',null=True)
    subtitulo = models.CharField(max_length=100,verbose_name='Subtitulo',blank=True)
    variation_category = models.CharField(max_length=200,verbose_name='Variacion', choices = variation_category_choices,default='Edicion')
    variation_value = models.CharField(max_length=200,verbose_name='Edicion')
    stock = models.IntegerField(verbose_name='Stock')
    image = models.ImageField(upload_to='photos/products',blank=True,verbose_name='URL_Imagen',null=True)
    is_active = models.BooleanField(default=True,verbose_name='Disponible')
    created_date = models.DateField(auto_now_add=True,verbose_name='Fecha de creacion')
    updated_date = models.DateField(auto_now=True,verbose_name='Fecha de actualizacion')
    precio_ed = models.DecimalField(max_digits=18,decimal_places=2,verbose_name='Precio Ed.',null=True,blank=True)
    
    objects = VariationManager()
    
    def get_url_2(self):
        return reverse('product_detail_2', args=[self.product.category.slug, self.product.slug,self.variation_value])
    
    def __str__(self):
        return self.variation_category + ": " + self.variation_value
    
    
    
    class Meta:
        verbose_name = "Edicion"
        verbose_name_plural = "Ediciones"
        constraints = [
            models.UniqueConstraint(
                fields=['product', 'variation_value'], name='id_titulo_edicion'
            )
        ]       

class Banner(models.Model):
    coleccion = models.CharField(max_length=100,verbose_name='Coleccion')
    image = models.ImageField(upload_to='photos/banners',verbose_name='URL_Imagen')
    is_active = models.BooleanField(default=True,verbose_name='Activo')
    
    class Meta:
        verbose_name = "Banner"
        verbose_name_plural = "Banners"

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='Producto',default=None)
    image = models.ImageField(upload_to='store/products',max_length=255,verbose_name='Imagenes')
    
    def __str__(self):
        return self.product.product_name
    

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from accounts.models import UserProfile
import datetime

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    
        
    current_user = request.user
    profile = UserProfile.objects.get(user=current_user)
    print("El profile es =" +str(profile))
    if current_user.is_authenticated:
        #aqui en este bloque agregaremos la logica del carrito de compras cuando
        #el usuario esta autenticado
        product_variation = []


        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()

        if is_cart_item_exists:
            print("cart item exists y esta login hecho!")
            cart_item = CartItem.objects.filter(product=product, user=current_user)

            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation  in ex_var_list:
                  index = ex_var_list.index(product_variation)
                  item_id = id[index]
                  item = CartItem.objects.get(product=product, id=item_id)
                  item.quantity += 1
                  item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0 :
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.profile=profile
                item.save()

        else:
            print("cart item does not exists y esta login hecho!")
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user
            )
            if len(product_variation) > 0 :
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.profile=profile
            cart_item.save()

        return redirect('cart')

    else:
        product_variation = []

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()



        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)

            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation  in ex_var_list:
                  index = ex_var_list.index(product_variation)
                  item_id = id[index]
                  item = CartItem.objects.get(product=product, id=item_id)
                  item.quantity += 1
                  item.profile=profile
                  item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0 :
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.profile=profile
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0 :
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.profile=profile
            cart_item.save()

        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2*total)/100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass ## solo ignora la exception

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax' : tax,
        'grand_total': grand_total
    }

    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    userProfile = UserProfile.objects.get(user=request.user)
    numero_vendedor = userProfile.numero_vendedor
    nombre_vendedor = userProfile.nombre_vendedor
    yr=int(datetime.date.today().strftime('%Y'))
    mt=int(datetime.date.today().strftime('%m'))
    dt=int(datetime.date.today().strftime('%d'))
    d = datetime.date(yr,mt,dt)
    current_date = d.strftime("%Y%m%d")
    print("antes de entrar al try: "+str(numero_vendedor))
    order_number = current_date+str(user.id)+str(numero_vendedor)
    try:

        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)



        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        
        grand_total = total

        user = request.user
         
        context ={
            'quantity': quantity,
            'cart_items': cart_items,
            'grand_total': grand_total,
            'numero_vendedor': numero_vendedor,
            'nombre_vendedor': nombre_vendedor,
            'order_number': order_number,
        }
        
    
    except ObjectDoesNotExist:
        pass ## solo ignora la exception
    print(numero_vendedor, nombre_vendedor)
    context ={
            'quantity': quantity,
            'cart_items': cart_items,
            'grand_total': grand_total,
            'numero_vendedor': numero_vendedor,
            'nombre_vendedor': nombre_vendedor,
            'order_number': order_number,
        }

    return render(request, 'store/checkout.html', context)

templates/store/product_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              {% if edicion.image.url %}
              <center><img id="imagen_ed" src="{{ edicion.image.url }}"></center>
              {% else %}
              <center><img id="imagen_ed" src="{{ single_product.images.url }}"></center>
              {% endif %}
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->

          <ul class="thumb">
              <li>
                  <a href="{{ single_product.images.url }}" target="mainImage"><img id="imagen_ed" src="{{single_product.images.url}}" alt="Imagen del producto">  </a>
                  {% for i in product_gallery %}
                      <a href="{{ i.image.url }}" target="mainImage"><img src="{{i.image.url}}" alt="Imagen del producto">  </a>
                  {% endfor %}
              </li>
          </ul>

        </aside>
        <main class="col-md-6 border-left">

          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            
            <article class="content-body">

              <h2 class="title">{{ single_product.product_name }}</h2>
              <div class="rating-star">
                  <span>
                        <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                  </span>
              </div>
              <span>  Comentarios </span>
<br>
<!--
              <div class="mb-2.5" style="font-size:1.5em;"><strong>{{ single_product.product_name }}</strong></div>
    -->          
              <div id="titulo" name="titulo" hidden>{{ single_product.id }}</div>
              
              {% if edicion.subtitulo %}
              <p id="subtitulo" name="subtitulo" class="mb-3" style="font-size:1.1em; color:grey;">{{edicion.subtitulo}}</p>
              {% else %}
              
              <p id="subtitulo" name="subtitulo" class="mb-3" style="font-size:1.1em; color:grey;font-weight: bold;"></p>
              {% endif %}
              <div class="mb-3">
                <span class="price h4">$ {{ single_product.price }}</span><span style="font-size:0.8em"> + {{single_product.recargo_interior}} (RI)</span>
              </div>

              <p> {{ single_product.description }} </p>


              <hr>

              <div class="row">
                <div class="item-option-select">
                  <h6>Seleccione Edición</h6>
                  <select class="form-control" id="edicion" name="edicion" required>
                    <option value="" disabled selected>Seleccione</option>
                    {% for i in single_product.variation_set.edicion  %}
                    {% if edicion.variation_value == i.variation_value %}
                    <option value="{{ i.variation_value | lower }}" selected>{{ i.variation_value | capfirst }}</option>
                    {% else %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endif %}
                    {% endfor %}
                  </select>
                </div>
              </div> 
              
<!--            

              <div class="row">
                <div class="item-option-select">
                  <h6>Seleccione Talla</h6>
                  <select class="form-control" name="talla" required>
                    <option value="" disabled selected>Seleccione</option>
                    {% for i in single_product.variation_set.tallas %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>  row.// 
-->
              <hr>
              <h5 id="sin_stock" style="color:red; font-size:0.9em;"></h5>
              <h5 id="poco_stock" style="color:blue; font-size:0.9em;"></h5>
              
              <button id="carrito" type="submit"  class="btn  btn-primary"> <span class="text">Agregar al Carrito</span> <i class="fas fa-shopping-cart"></i>  </button>
              
            </article> <!-- product-info-aside .// -->

          </form>



        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">

        <form action="{% url 'submit_review' single_product.id %}" method="post">
          {% csrf_token %}
          <h5>Escribe Tu Comentario</h5>

          <div class="">
            <label for="">Como calificarias este producto?</label>
            <br>
            <div class="rate">
                <input type="radio" name="rating" value="5" id="rating10"><label for="rating10" title="5"></label>
                <input type="radio" name="rating" value="4.5" id="rating9"><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" value="4" id="rating8"><label for="rating8" title="4"></label>
                <input type="radio" name="rating" value="3.5" id="rating7"><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" value="3" id="rating6"><label for="rating6" title="3"></label>
                <input type="radio" name="rating" value="2.5" id="rating5"><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" value="2" id="rating4"><label for="rating4" title="2"></label>
                <input type="radio" name="rating" value="1.5" id="rating3"><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" value="1" id="rating2"><label for="rating2" title="1"></label>
                <input type="radio" name="rating" value="0.5" id="rating1"><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>

            Titulo de comentario:
            <input type="text" class="form-control" name="subject" value="">
            <br>

            Comentario:
            <textarea name="review" rows="4" class="form-control" ></textarea>
            <br>
            {% if user.is_authenticated %}

              {% if orderproduct %}
                <input type="submit" name="" value="Enviar Comentario" class="btn btn-primary">
              {% else %}
                <p>Debe primero comprar el producto para poder enviar un comentario</p>
              {% endif %}

            {% else %}
              <p>Para enviar un comentario debes estar registrado <span><a href="{% url 'login' %}"> Inicia Sesion </a></span></p>
            {% endif %}
          </div>

          {% include 'includes/alerts.html' %}

        </form>
      

        <header class="section-heading">
          <h3>Calificacion de Clientes </h3>

          <div class="rating-star">
              <span>
                    <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
              </span>
          </div>



        </header>
        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <div class="text">
              <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
              <h6 class="mb-1">{{ review.user.full_name }}</h6>
              <div class="rating-star">
                  <span>
                        <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                  </span>
              </div>
            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>
              {{ review.review }}
            </p>
          </div>
        </article>
        {% endfor %}


      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<script>
 // Funcion que debe estar siempre 
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

$("#edicion").change(function (e) {
  e.preventDefault();
  var edicion = $("#edicion").val();
  //alert("edicion="+edicion)
  var titulo = $("#titulo").text();
  //alert("titulo="+titulo)
  var urls="http://127.0.0.1:8000/store/get_ajax_titulo/"
  var url = new URL(urls),
    params = {titulo:titulo, edicion:edicion};
Object.keys(params).forEach(key => url.searchParams.append(key, params[key]))
  //alert(url);

    fetch(url, {
      headers:{
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
      },
      method: 'GET',     
  })
  .then(response => response.json())
  .then(data => {
  console.log(data)
  var content = data;
  console.log("content="+content.data.subtitulo);
  document.getElementById('subtitulo').innerHTML=content.data.subtitulo;
  console.log("imagen="+content.data.image);
  var img = document.getElementById('imagen_ed')
  img.src = content.data.image;  
  console.log("stock="+content.data.stock);
  document.getElementById('poco_stock').innerHTML="Quedan "+ content.data.stock +" en stock";
  document.getElementById('sin_stock').innerHTML="Producto fuera de stock";
  if (content.data.stock <= 0) {
    document.getElementById('carrito').hidden=true;
    document.getElementById('sin_stock').hidden=false;
    document.getElementById('poco_stock').hidden=true;
  }else if (content.data.stock > 0 && content.data.stock < 6 ) {
    document.getElementById('carrito').hidden=false;
    document.getElementById('sin_stock').hidden=true;
    document.getElementById('poco_stock').hidden=false;
  }else{
    document.getElementById('carrito').hidden=false;
    document.getElementById('sin_stock').hidden=true;
    document.getElementById('poco_stock').hidden=true;
  }
});

});

</script>



{% endblock %}